exclude: ['README.md']
timezone: US/Pacific

markdown:         kramdown
highlighter:      pygments

permalink:            pretty

title:            Anoop Sarkar
tagline:          'slow train coming ...'
#url:              http://anoopsarkar.github.io
url:              http://127.0.0.1:4000/
baseurl:          /
assets:           /assets/
imageurl:         /assets/images/
fileurl:          /assets/files/
cssurl:           /assets/css/

author:
  name:           'Anoop Sarkar'
  github:         https://github.com/anoopsarkar
  bitbucket:      https://bitbucket.org/sfu-natlang
  twitter:        https://twitter.com/anoopsarkar

github:
  repo:           https://github.com/anoopsarkar/anoopsarkar.github.io
