#!/bin/bash

set -e

if [ $# != 1 ]; then
    echo "usage: $0 GROUP-DIRNAME" 1>&2
    echo "for example, $0 CMPT379-1127-g-YOUR_GROUP_NAME"
    exit 1
fi
dirname=$1 # for example, CMPT379-1127-g-203
coursesvn="https://punch.cs.sfu.ca/svn/$dirname" 
svndir="sfu-compilers-read-only"
hwname="hw1"
hwdir="$dirname/$hwname"

if [ -f "$svndir" ]; then
    echo "use a different directory or remove file $svndir"
    exit 1
fi

if [ -f "$hwdir" ]; then
    echo "use a different directory or remove file $hwdir"
    exit 1
fi

if [ -d "$svndir" ]; then
    pushd "$svndir" > /dev/null
    if svn update; then
        echo "$svndir updated"
    else
        popd > /dev/null
        echo "$svndir should not exist here. Move or delete this directory and try again."
        exit 1
    fi
    popd > /dev/null
else
    svn checkout http://sfu-compilers.googlecode.com/svn/trunk/ "$svndir"
fi 1>&2

if [ -d "$hwdir" ]; then
    echo "$dirname already exists. updating ..."
    pushd "$dirname" > /dev/null
    svn update
    popd > /dev/null
else
    echo "$dirname does not exist. creating ..."
    if svn checkout "$coursesvn" "$dirname"; then
        echo "$dirname created"
    else
        echo "bad group name $dirname"
        /bin/rm -rf "$svndir"
        exit 1
    fi
fi 1>&2

echo "rsync ..." 1>&2
rsync -Cpav "$svndir/$hwname" "$dirname" 1>&2

echo 1>&2
echo 1>&2
echo "Put your solutions in the directory: $hwdir/answer" 1>&2
echo "Execute the following svn commands to save your work:" 1>&2
echo 1>&2
echo "cd $dirname"

updir=$PWD
pushd "$dirname" > /dev/null
if [ -d "$updir/$svndir" ]; then
    svn status | grep '^?' | awk '{print $2}' | while read f; do 
        if [ -a "$updir/$svndir/$f" ]; then 
            echo "svn add $f"; 
        fi; 
    done
else
    echo "Error: $updir/$svndir is missing." 1>&2
fi
popd > /dev/null
echo "svn commit -m 'did pull-hw1 to get hw1 files'"
echo

/bin/rm -rf "$svndir"
exit 0
